version: '3.8'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=souheyl.gouadria@supcom.tn
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    depends_on:
      - postgres
      - compiler-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/coding
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      COMPILER_SERVICE_URL: "http://compiler-service:8082"
    links:
      - postgres
    restart: on-failure


  compiler-service:
    build:
      context: D:\java learning\Compiler
      dockerfile: Dockerfile
    container_name: compiler-service
    depends_on:
      - postgres
      - judge0-server
    ports:
      - "8082:8082"
    environment:
      JUDGE_URL: "http://judge0-server:2358"
    restart: on-failure



  api-gateway:
    build:
      context: D:\java learning\ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - spring-app
    ports:
      - "8080:8080"
    environment:
      CODING_SERVICE_URI: "http://spring-app:8081"
    restart: on-failure


  # Judge0 services
  judge0-server:
    image: judge0/judge0:1.13.1
    container_name: judge0-server
    volumes:
      - D:\java learning\judge0-v1.13.1\judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

  judge0-workers:
    image: judge0/judge0:1.13.1
    container_name: judge0-workers
    command: [ "./scripts/workers" ]
    volumes:
      - D:\java learning\judge0-v1.13.1\judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  judge0-db:
    image: postgres:latest
    container_name: judge0-db
    volumes:
      - judge0-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: very_hard_password
      POSTGRES_DB: judge0
    restart: always
    ports:
      - "5433:5432"

  judge0-redis:
    image: redis:7.2.4
    container_name: judge0-redis
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file:
      - D:\java learning\judge0-v1.13.1\judge0.conf
    <<: *default-logging
    restart: always

volumes:
  judge0-data:
